apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t2x628bxq-go 
  janus-idp.io/tekton: t2x628bxq-go
  backstage.io/kubernetes-id: t2x628bxq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t2x628bxq-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  